### ISSUE TITLE
global-buffer-overflow in send_packets

### ISSUE THREAD

**Issue by vodik** [SIPp/sipp#162]
~~~
ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000008eb300 at pc 0x0000004b135e bp 0x7f110fdfe5a0 sp 0x7f110fdfe590
READ of size 4 at 0x0000008eb300 thread T1
    #0 0x4b135d in send_packets src/send_packets.c:159
    #1 0x431837 in send_wrapper(void*) src/call.cpp:4259
    #2 0x7f1114852353 in start_thread (/usr/lib/libpthread.so.0+0x7353)
    #3 0x7f111388bbfc in __clone (/usr/lib/libc.so.6+0xe7bfc)
~~~

**Comment by wdoekes** [comment]
Wow. That looks like it would've been hard to find. Thanks for catching that.
