### ISSUE TITLE
Assertion 'sock' failed

### ISSUE THREAD

**Issue by foucse** [SIPp/sipp#217]
```
SIPp v3.6-dev-28-g21100ac-RTPSTREAM built Mar 31 2016, 14:36:21
```

On one of my testing machines I have frequently the following error:

```
sipp: src/sipp.cpp:498: void pollset_process(int): Assertion `sock' failed.
```

Which is, from what I understand an assertion on one of the open sockets, after what it is core dumping.

src/sipp.cpp:498
```C++
    /* We need to flush all sockets and pull data into all of our buffers. */
#ifdef HAVE_EPOLL
    for (int event_idx = 0; event_idx < rs; event_idx++) {
        int poll_idx = (int)epollevents[event_idx].data.u32;
#else
    for (size_t poll_idx = 0; rs > 0 && poll_idx < pollnfds; poll_idx++) {
#endif
        struct sipp_socket *sock = sockets[poll_idx];
        int events = 0;
        int ret = 0;

        assert(sock);
```

Unfortunately, I have nothing useful in my core file:

```
Reading symbols from /usr/local/bin/sipp...done.
[New LWP 12203]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Core was generated by `sipp example.com:5060 -sf /home/user1/F/scenario-a-1.xml'.
Program terminated with signal SIGABRT, Aborted.
#0  0xb771ccb0 in ?? ()
```

```
(gdb) bt full
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x9:
#0  0xb771ccb0 in ?? ()
No symbol table info available.
Cannot access memory at address 0x9
```

Possible causes ?

**Comment by wdoekes** [comment]
Could you try the --without-epoll option on configure?

Not sure if it helps, but it might make a difference.

**Comment by wdoekes** [comment]
Cannot reproduce without more info.
