### ISSUE TITLE
Crash when sending a 3pcc cmd message

### ISSUE THREAD

**Issue by foucse** [SIPp/sipp#268]
I am using SIPp 8987f69f60d40da1a4c1055eb54758efe3263fc2

I have the following crash when sending a 3pcc cmd message, which is not always reproducible:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  SIPpSocket::write (this=0x0, buffer=buffer@entry=0x673980 <call::createSendingMessage(SendingMessage*, int, int*)::msg_buffer> "Call-ID:  88-6765@10.37.145.153\r\nFrom: alice\r\n\r\n\033", len=49,
    flags=flags@entry=2, dest=dest@entry=0x1144690) at src/socket.cpp:2373

#0  SIPpSocket::write (this=0x0, buffer=buffer@entry=0x673980 <call::createSendingMessage(SendingMessage*, int, int*)::msg_buffer> "Call-ID:  88-6765@10.37.145.153\r\nFrom: alice\r\n\r\n\033", len=49,
    flags=flags@entry=2, dest=dest@entry=0x1144690) at src/socket.cpp:2373
        rc = <optimized out>
        currentTime = {tv_sec = 16938200, tv_usec = 5724662524668402688}
#1  0x0000000000413828 in call::sendCmdMessage (this=this@entry=0x1144680, curmsg=curmsg@entry=0xfd6a70) at src/call.cpp:1841
        rc = <optimized out>
        dest = 0x673980 <call::createSendingMessage(SendingMessage*, int, int*)::msg_buffer> "Call-ID:  88-6765@10.37.145.153\r\nFrom: alice\r\n\r\n\033"
        delimitor = "\033"
        peer_dest = <optimized out>
        peer_socket = 0xfc73b0
#2  0x00000000004165a9 in call::executeMessage (this=0x1144680, curmsg=0xfd6a70) at src/call.cpp:1215
        send_status = <optimized out>
#3  0x0000000000408533 in traffic_thread () at src/sipp.cpp:560
        running_tasks = 0x7f8280 <running_tasks>
        loops = 999
        last = <optimized out>
        iter = {_M_node = 0x7f8280 <running_tasks>}
        L_file_name = "xxxxxxxxxxx"...
#4  main (argc=<optimized out>, argv=0x7ffc3b8c1c58) at src/sipp.cpp:1994
        media_sockaddr = {ss_family = 2, __ss_align = 0, __ss_padding = '\000' <repeats 111 times>}
        pthread3_id = 0
        generic_count = 1
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        argi = <optimized out>
        pthread2_id = 0
        slave_masterSet = true
```

Any ideas ?

upd: updated stack trace 07/11/2016

Looks like the variable ss_out dereferences some strange address and is corrupted for some reason:

```
(gdb) p ss_out
Cannot access memory at address 0xb8
```

**Comment by wdoekes** [comment]
I hope this has been fixed by now. Please re-open if this is still an issue with up-to-date branch/3.5 or master.
