### ISSUE TITLE
segfault in send_packets

### ISSUE THREAD

**Issue by davehorton** [SIPp/sipp#576]
Built the latest from source, its crashing on me.

```
Core was generated by `sipp -sf uac_pcap_60s_call.xml -r 20 -m 500 -l 300 -s 555 3.120.157.16'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563daf999838 in send_packets (play_args=0x563db050dff0) at /usr/local/src/sipp/src/send_packets.c:261
261	        memcpy(udp, pkt_index->data, pkt_index->pktlen);
[Current thread is 1 (Thread 0x7f6dffd1c700 (LWP 10302))]
(gdb) bt
#0  0x0000563daf999838 in send_packets (play_args=0x563db050dff0) at /usr/local/src/sipp/src/send_packets.c:261
#1  0x0000563daf9652b4 in send_wrapper (arg=0x563db050dff0) at /usr/local/src/sipp/src/call.cpp:6818
#2  0x00007f6e21573fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#3  0x00007f6e21133eff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) l
256	     * allows the thread to be cancelled cleanly.
257	     */
258	    pthread_cleanup_push(send_packets_cleanup, ((void *) &sock));
259
260	    while (pkt_index < pkt_max) {
261	        memcpy(udp, pkt_index->data, pkt_index->pktlen);
262	        port_diff = ntohs(udp->uh_dport) - pkts->base;
263	        /* modify UDP ports */
264	        udp->uh_sport = htons(port_diff + ntohs(*from_port));
265	        udp->uh_dport = htons(port_diff + ntohs(*to_port));
```

latest master branch
```
f44d0cf (HEAD -> master, origin/master, origin/HEAD) docs: Change scenario in CHANGES.md to one that works
```

is this a known issue?

**Comment by davehorton** [comment]
perfectly recreatable under load by the way

**Comment by MichaelSekora** [comment]
Hi Dave,
I try to reproduce the scenario, could you please provide "uac_pcap_60s_call.xml", I cannot find it in the example scenarios, etc.
Do you have a sip-trace? how does the other side respond (connected with 200 OK)?
