### ISSUE TITLE
sigsegv on ereg within nop ( sipp 3.7.2 )

### ISSUE THREAD

**Issue by gitkoyot** [SIPp/sipp#671]
Hi,
sipp version is 3.7.2 (debian/testing)
I had a complicated scenario with lots of "ifs" and "else" (in xml) and under certain conditions the UAS part of it crashed with sigsegv. I was able to trace it to following(similar) part of the script.

If you put it to standard uas script you should also get similar result.
```
  <nop>
	  <action>
	   <ereg regexp="thisIsJustToFailSippScenario" search_in="hdr" header="NonExisting:" check_it="true"
		                     assign_to="unused"/>
		  <log message="This is value of [$unused]"/>
	  </action>
  </nop>
```

I know this is my error. But it took me ages to trace this. I used gdb/valgrind:

```
Thread 1 "sipp" received signal SIGSEGV, Segmentation fault.8e6c0 (LWP 16296)]
                                                            0x00005555555708a3 in call::extractSubMessage (this=this@entry=0x5555558fe9a0, msg=msg@entry=0x0, 
    matchingString=0x55555581c9f0 "NonExisting:", result=result@entry=0x7fffffffdb80 "\b\253^UUU", case_indep=false, 
    occurrence=occurrence@entry=1, headers=false) at ./src/call.cpp:6492
6492	./src/call.cpp: No such file or directory.
(gdb) bt
#0  0x00005555555708a3 in call::extractSubMessage (this=this@entry=0x5555558fe9a0, msg=msg@entry=0x0, 
    matchingString=0x55555581c9f0 "NonExisting:", result=result@entry=0x7fffffffdb80 "\b\253^UUU", case_indep=false, 
    occurrence=occurrence@entry=1, headers=false) at ./src/call.cpp:6492
#1  0x000055555557ad56 in call::executeAction (this=this@entry=0x5555558fe9a0, msg=msg@entry=0x0, curmsg=curmsg@entry=0x55555581bd50)
    at ./src/call.cpp:5606
#2  0x000055555557e49d in call::executeMessage (this=0x5555558fe9a0, curmsg=0x55555581bd50) at ./src/call.cpp:1900
#3  0x00005555555654c6 in traffic_thread (echo_errors=<synthetic pointer>: 0, rtp_errors=<synthetic pointer>: 0) at ./src/sipp.cpp:589
#4  main (argc=<optimized out>, argv=<optimized out>) at ./src/sipp.cpp:2147
```

**Comment by wdoekes** [comment]
I cannot crash current master with this.

@gitkoyot: can you reproduce with current master, and if so, how exactly?
